
# Configuration of AutoEncoder using KL-reg, when using Cifars
# Downsample the resolution 3x32x32 --> 3x16x16

model:
  base_learning_rate: 4.5e-6
  target: ldm.models.autoencoder.AutoencoderKL
  params:
    monitor: "val/rec_loss"
    embed_dim: 3

    ddconfig:
      double_z: True
      z_channels: 3
      resolution: 32
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult: [ 1,2 ]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: [ 16,8,4 ]
      dropout: 0.0


lossconfig:
  target: ldm.modules.losses.LPIPSWithDiscriminator
  params:
    disc_start: 50001
    kl_weight: 0.000001
    disc_weight: 0.5

data:
  target: main.DataModuleFromConfig
  embed_dim: [3, 16, 16]
  params:
    batch_size: 64
    wrap: True
    train:
      target: datasets.Cifars
      params:
        size: 32
        degradation: pil_nearest
    validation:
      target: datasets.Cifars
      params:
        size: 32
        degradation: pil_nearest

